Project Completed(News Week Clone)
Zappat0n/Newsweek-clone pull request #1
Opened 2020-11-05 14:45 UTC by iam-Akshat

### Made using Bootstrap and CSS

- Used d-flex and various other bootstrap classes to position the content without using CSS.
- Used row and columns to design the front page and to make it responsive.
- Used Sass for better maintainability of CSS.

2020-11-05 17:31 UTC, MuriloRoque requested changes
## Status: Changes Requested 🔴 

### Hello @iam-Akshat and @Zappat0n 👋 

### Your project is so nice, I barely could find anything to review, congratulations 👏 

### We only need to fix some details about the clone and one issue in your code, please check my comments:

- [ ] On big screens, your navigation bar is smaller than the original, please make the links and search bar 'spread' around the full width:

**Yours:**

![Yours1](https://user-images.githubusercontent.com/59691171/98274858-b6e31400-1f72-11eb-95a3-4fd6476fc7da.png)

**Original:**

![Original1](https://user-images.githubusercontent.com/59691171/98274894-c19da900-1f72-11eb-83f0-56f98e499288.png)

- [ ] On big and medium screens, the elements inside of the "subscribe" section are not positioned like the original, please take a look at the screenshots below:

**Yours (big):**

![Yours2](https://user-images.githubusercontent.com/59691171/98275064-f90c5580-1f72-11eb-967a-871acac41b00.png)

**Original (big):**

![Original2](https://user-images.githubusercontent.com/59691171/98275094-04f81780-1f73-11eb-98a7-bc23f243946b.png)

**Yours (medium):**

![Yours3](https://user-images.githubusercontent.com/59691171/98275121-0de8e900-1f73-11eb-8c31-9ac757f07700.png)

**Original (medium):**

![Original3](https://user-images.githubusercontent.com/59691171/98275167-1b05d800-1f73-11eb-9137-11250ca85913.png)

- [ ] On small screens, the only issue is the resolution of the images, as they are too big, and you probably got the small versions of them, so please try getting the big ones, take a look below:

![yours4](https://user-images.githubusercontent.com/59691171/98275273-3e308780-1f73-11eb-8315-9efe21c6bcff.png)

- [ ] Please check my comment in your code.

## Summary

- Your code is very good and organized, bonus points for working with SCSS so early 😄 
- Your repository is very professional, keep up the good work 💪 
- We only need to finish some minor issues before moving on 🚀 

Kindly make the requested changes and submit for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-11-05 17:31 UTC, MuriloRoque commented on styles.css
> +/* stylelint-disable */
- [ ] Please don't disable the linters, they are here to help you write better code.

2020-11-06 14:18 UTC, Zappat0n commented
Thanks for the review.
We have already committed the changes and requested a new review.
Best regards.

2020-11-06 16:00 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello again @iam-Akshat and @Zappat0n  :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-11-06 16:06 UTC, merged